spring.application.name=labs

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

jwt.secret=3ee28689140b028d88559848a8293be208eae3d7d7dd83b76bd173eba6c61306
jwt.access.expiration=3600000
jwt.refresh.expiration=4536000000

cookie.access.expiration=3600
cookie.refresh.expiration=2592000